---
# handlers file for nginx
- name: check_url_response
  uri:
    url: "{{item.a}}"
    status_code: "{{item.b}}"
  with_items:
    - {a: "{{server1}}" ,b: "{{status1}}"}
    - {a: "{{Server2}}" , b: "{{status1}}"}
...
